# -*- coding: utf-8 -*-
"""Motyle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxjJO-2f96X-ZM9aXcMqt8FHiyiVrt2z
"""

!pip install transformers datasets torch accelerate scikit-learn -q

import pandas as pd
import numpy as np

from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import Trainer, TrainingArguments, DataCollatorWithPadding
from sklearn.metrics import accuracy_score, f1_score


# =========================
# 1. Load project data
# =========================

url = "https://github.com/zgompert/MontaneButterfliesLTREB/raw/refs/heads/master/Shapiro_Counts.csv.gz"
df = pd.read_csv(url)

# CHECK DATA
print("First rows:")
print(df.head())

print("\nColumns:")
print(df.columns)

print("\nShape:")
print(df.shape)


# =========================
# 2. Use only years 2000-2016
# =========================

df = df[(df["year"] >= 2000) & (df["year"] <= 2016)]


# =========================
# 3. Aggregate count by species and year
# =========================

species_year = (
    df.groupby(["genus_species", "year"])["count"]
    .sum()
    .reset_index()
)


# =========================
# 4. Get count in 2000 and 2016 for each species
# =========================

pivot = species_year.pivot(
    index="genus_species",
    columns="year",
    values="count"
).fillna(0)

# This is safer than pivot[[2000, 2016]]
# because it prevents errors if one of the columns is missing.
pivot = pivot.reindex(columns=[2000, 2016], fill_value=0).reset_index()

pivot.columns = ["genus_species", "count_2000", "count_2016"]


# =========================
# 5. Calculate percentage change
# =========================

pivot["percent_change"] = np.where(
    pivot["count_2000"] == 0,
    0,
    ((pivot["count_2016"] - pivot["count_2000"]) / pivot["count_2000"]) * 100
)


# =========================
# 6. Create labels
# 0 = decreasing
# 1 = stable
# 2 = increasing
# =========================

def create_label(change):
    if change > 10:
        return 2
    elif change < -10:
        return 0
    else:
        return 1


pivot["label"] = pivot["percent_change"].apply(create_label)


# =========================
# 7. Create text input for model
# =========================

pivot["text"] = (
    "Species: " + pivot["genus_species"].astype(str) +
    ". Count in 2000: " + pivot["count_2000"].astype(str) +
    ". Count in 2016: " + pivot["count_2016"].astype(str) +
    ". Percentage change: " + pivot["percent_change"].round(2).astype(str) + "%."
)


# =========================
# 8. Keep only text and label
# =========================

data = pivot[["text", "label"]]

print("\nPrepared data:")
print(data.head())

print("\nLabel distribution:")
print(data["label"].value_counts())


# =========================
# 9. Convert pandas DataFrame to Hugging Face Dataset
# =========================

hf_dataset = Dataset.from_pandas(data)


# =========================
# 10. Train/test split
# =========================

hf_dataset = hf_dataset.train_test_split(test_size=0.2, seed=42)


# =========================
# 11. Load model and tokenizer
# =========================

model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3
)


# =========================
# 12. Tokenize data
# =========================

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True
    )


tokenized_dataset = hf_dataset.map(tokenize_function, batched=True)

# Remove text column after tokenization
tokenized_dataset = tokenized_dataset.remove_columns(["text"])

# Padding is handled automatically during training
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)


# =========================
# 13. Metrics
# =========================

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    accuracy = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average="macro")

    return {
        "accuracy": accuracy,
        "f1_macro": f1
    }


# =========================
# 14. Training arguments
# =========================

training_args = TrainingArguments(
    output_dir="./butterfly_trend_model",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="no",
    report_to="none"
)


# =========================
# 15. Trainer
# =========================

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)


# =========================
# 16. Fine-tune model
# =========================

trainer.train()


# =========================
# 17. Evaluate model
# =========================

results = trainer.evaluate()

print("\nEvaluation results:")
print(results)


# =========================
# 18. Save model
# =========================

trainer.save_model("./butterfly_trend_model")
tokenizer.save_pretrained("./butterfly_trend_model")

print("\nModel saved to: ./butterfly_trend_model")

import torch

label_names = {
    0: "decreasing",
    1: "stable",
    2: "increasing"
}

def predict_trend(species_name, count_2000, count_2016):
    if count_2000 == 0:
        percent_change = 0
    else:
        percent_change = ((count_2016 - count_2000) / count_2000) * 100

    text = (
        f"Species: {species_name}. "
        f"Count in 2000: {count_2000}. "
        f"Count in 2016: {count_2016}. "
        f"Percentage change: {percent_change:.2f}%."
    )

    inputs = tokenizer(text, return_tensors="pt", truncation=True)
    inputs = {key: value.to(model.device) for key, value in inputs.items()}

    model.eval()

    with torch.no_grad():
        outputs = model(**inputs)
        prediction = torch.argmax(outputs.logits, dim=-1).item()

    return {
        "text": text,
        "prediction_id": prediction,
        "prediction_label": label_names[prediction]
    }


result = predict_trend(
    species_name="Example butterfly",
    count_2000=100,
    count_2016=50
)

print(result)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

predictions = trainer.predict(tokenized_dataset["test"])

y_true = predictions.label_ids
y_pred = np.argmax(predictions.predictions, axis=1)

print("Classification report:")
print(classification_report(
    y_true,
    y_pred,
    target_names=["decreasing", "stable", "increasing"]
))

print("Confusion matrix:")
print(confusion_matrix(y_true, y_pred))