# -*- coding: utf-8 -*-
"""Motyle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxjJO-2f96X-ZM9aXcMqt8FHiyiVrt2z
"""

!pip install transformers datasets torch -q

import pandas as pd
import numpy as np

# CHECK DATA
print(df.head())
print(df.columns)
print(df.shape)

from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import Trainer, TrainingArguments

# 1. Load project data
url = "https://github.com/zgompert/MontaneButterfliesLTREB/raw/refs/heads/master/Shapiro_Counts.csv.gz"
df = pd.read_csv(url)

# 2. Use only years 2000-2016
df = df[(df["year"] >= 2000) & (df["year"] <= 2016)]

# 3. Aggregate count by species and year
species_year = (
    df.groupby(["genus_species", "year"])["count"]
    .sum()
    .reset_index()
)

# 4. Get count in 2000 and 2016 for each species
pivot = species_year.pivot(
    index="genus_species",
    columns="year",
    values="count"
).fillna(0)

# Keep only species that have columns for 2000 and 2016
pivot = pivot[[2000, 2016]].reset_index()
pivot.columns = ["genus_species", "count_2000", "count_2016"]

# 5. Calculate percentage change
pivot["percent_change"] = np.where(
    pivot["count_2000"] == 0,
    0,
    ((pivot["count_2016"] - pivot["count_2000"]) / pivot["count_2000"]) * 100
)

# 6. Create labels
# 0 = decreasing, 1 = stable, 2 = increasing
def create_label(change):
    if change > 10:
        return 2
    elif change < -10:
        return 0
    else:
        return 1

pivot["label"] = pivot["percent_change"].apply(create_label)

# 7. Create text input for LLM
pivot["text"] = (
    "Species: " + pivot["genus_species"].astype(str) +
    ". Count in 2000: " + pivot["count_2000"].astype(str) +
    ". Count in 2016: " + pivot["count_2016"].astype(str) +
    ". Percentage change: " + pivot["percent_change"].round(2).astype(str) + "%."
)

# 8. Keep only text and label
data = pivot[["text", "label"]]

print(data.head())
print(data["label"].value_counts())

# 9. Convert pandas DataFrame to Hugging Face Dataset
hf_dataset = Dataset.from_pandas(data)

# 10. Train/test split
hf_dataset = hf_dataset.train_test_split(test_size=0.2, seed=42)

# 11. Load model and tokenizer
model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3
)

# 12. Tokenize data
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True
    )

tokenized_dataset = hf_dataset.map(tokenize_function, batched=True)

# 13. Training arguments
training_args = TrainingArguments(
    output_dir="./butterfly_trend_model",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="no",
    report_to="none"
)

# 14. Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"]
)

# 15. Fine-tune model
trainer.train()

# 16. Evaluate model
results = trainer.evaluate()

print("Eval loss:", results["eval_loss"])